[build]
  functions = "functions"

[functions]
  node_bundler = "esbuild"

[functions]
directory = "functions"

[[redirects]]
  from = "/.netlify/functions/send-confirmation"
  to = "/.netlify/functions/send-confirmation"
  status = 200
